version: '3.9'

services:
  db:
    image: postgres:16-alpine3.19
    container_name: db
    ports:
      - '5433:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/vat/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 10s
      retries: 5

  web-dev:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: test
    container_name: web-dev
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  web-prod:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: prod
    container_name: web-prod
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy
